name: Main CI workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

        ocaml-compiler:
          - 4.12.x
#          - 4.13.x
          - 4.14.x
          - 5.3.x
          - 5.4.x
          - 5.5.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install GNU bash, sed, diff w/color, and setup timeout
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install bash
          brew install gnu-sed
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
          brew install diffutils
          brew install coreutils
          echo "$(brew --prefix)/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH
          echo "$PATH"
          echo `which timeout`
#         ls /usr/local/opt/coreutils/libexec/gnubin

      - run: opam install . --deps-only

      - run: opam install .

      - run: opam reinstall . --deps-only --with-test

      - run: opam reinstall . --with-test
